### ISSUE TITLE
integration not found

### ISSUE THREAD

**Issue by pickeld** [eyalcha/read_your_meter#4]
## Configuration

```

read_your_meter:
  host: http://localhost:4444
  username: xx@xx.com
  password: xx
  daily:
    - 0
    - 1
    - 2
    - 3
  monthly:
    - 0
    - 1
    - 2
    - 3    

```

## Describe the bug
after upgrading to 2021.6.0 from 2021.5.5
when checking for configutation validation, it says:
"Component error: read_your_meter - Integration 'read_your_meter' not found."

## Debug log

```text
2021-06-03 23:17:31 ERROR (SyncWorker_3) [homeassistant.loader] Error parsing manifest.json file at /config/custom_components/read_your_meter/manifest.json: Expecting property name enclosed in double quotes: line 9 column 1 (char 209)

2021-06-03 23:17:33 ERROR (MainThread) [homeassistant.setup] Setup failed for read_your_meter: Integration not found.


```

when trying to restart the system:

```
2021-06-03 23:27:47 ERROR (MainThread) [homeassistant.components.hassio] The system cannot restart because the configuration is not valid: Component error: read_your_meter - Integration 'read_your_meter' not found.
2021-06-03 23:27:47 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140478336601440] The system cannot restart because the configuration is not valid: Component error: read_your_meter - Integration 'read_your_meter' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 518, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: read_your_meter - Integration 'read_your_meter' not found.
```

**Comment by pickeld** [comment]
add "version": "<VERSION_NUMBER>"
to manifest.json file.
